### ISSUE TITLE
No back or forward buttons?

### ISSUE THREAD

**Issue by 990xan** [adriankarlen/textfox#10]
Hi! I love the theme but it seems like it hides the back and forward buttons, requiring you to find space on the page where you can right click and use the context menu to use them? I've tried removing the lines back-button, forward-button lines in navbar.css (lines 30 and 31) but it doesn't seem to bring them back. Any chance of there being some way to enable them in the future? The theme is currently unusable for me right now.

**Comment by adriankarlen** [comment]
I see that you closed this as not planned, personally I don't use any ui buttons for navigation so no this is not planned, per se, but I'll make sure to add a section to the readme regarding this.

For context, in https://github.com/adriankarlen/textfox/blob/d0143142f211e91e9120d8f225530510a0d5dd68/navbar.css#L30-L31 is where they are hidden. Remove those lines and navigation buttons should appear for you.
