### ISSUE TITLE
[FEATURE] - Styling of context menus

### ISSUE THREAD

**Issue by adriankarlen** [adriankarlen/textfox#19]
At the moment the only styling that is done is the addition of icons (courtesy of ShyFox).

**Comment by sikehish** [comment]
Is there any particular style that we need to adhere to? Could you provide some clarity?

**Comment by adriankarlen** [comment]
Hi @sikehish, absolutely. 

I'm not that strict on exact implementation and if everything uses available variables from `variables.css` (in this case it should be: `--accent`, `--bg`, `--border`, `--border-width` and `--rounding`) then I think the look of it would match the rest of the theme almost instantly.

"Code style": Replace variables instead of overwriting them for each selector wherever possible.

I don't think context menus should have a "title" like the sections of the app.
