### ISSUE TITLE
[FEATURE] - Support horizontal tabs

### ISSUE THREAD

**Issue by adriankarlen** [adriankarlen/textfox#23]
If the user does not have sidebery enabled, the horizontal tabs should be shown, and in the same styling

**Comment by 909oce** [comment]
ive been working on my own version of this for a bit, decided to upload it to github recently, feel free to grab ideas/code from mine if needed

https://github.com/909oce/firefox-tui

its pretty much the same thing as yours but without sideberry as i prefer horizontal tabs.

**Comment by adriankarlen** [comment]
Resolved in #32
