### ISSUE TITLE
[BUG] Tab gets halved in size when pinned

### ISSUE THREAD

**Issue by AinGrace** [adriankarlen/textfox#26]
![image](https://github.com/user-attachments/assets/b5f3c55f-db39-4888-87e5-87544b51f335)

![image](https://github.com/user-attachments/assets/c34b0094-f83d-4be3-82a6-3f434e33ec51)

**Comment by adriankarlen** [comment]
Hmm, this seems odd. Could you check if you have any css set in the style editor of sidebery?

**Comment by AinGrace** [comment]
Sorry for late response. Everything is off

**Comment by adriankarlen** [comment]
I was able to reproduce this issue by setting "Show titles of pinned tabs" to on in the sidebery config. For the styling to work it needs to be turned off.
![image](https://github.com/user-attachments/assets/9e15bab5-ec57-4fa7-b826-c50b09b60a1a)

At the moment I don't have plans to support pinned tab titles, so I'll close the issue, but if anyone want to take a crack at it they're welcome to.
