### ISSUE TITLE
#8 still persists on MacOS Firefox 131.0.3

### ISSUE THREAD

**Issue by oaroki-git** [adriankarlen/textfox#29]
Issues ~~#5~~ and #8 are still here after my installation, the colors are not set, and there is some ui overlap:
![# 2024-10-20 at 10 01 13](https://github.com/user-attachments/assets/18800868-10c6-4c5f-9f0a-dbfdb1464901)

additionally, sideberry seems to not be themed properly as well

Here is the file structure of my install:
<img width="682" alt="image" src="https://github.com/user-attachments/assets/09662d46-0e66-444f-8bc5-95a25ecb9fc0">

I'm new to firefox theming, so there is a good possibility that i'm missing something

**Comment by adriankarlen** [comment]
Move the user.js file outside of your chrome folder and see if that helps

**Comment by oaroki-git** [comment]
unfortunately it doesn't seem to help 

and i've tried just about every combination of toggling the changes in about:config written in the user.js to no avail

**Comment by oaroki-git** [comment]
i wonder if this is just firefox macos weirdness..

**Comment by oaroki-git** [comment]
holy shit... i'm an idiot. 

i was just on an older version.. most of it is fixed now.

still default colors though, would you happen to know what could cause this? (or what stupidly obvious thing i could have missed like what i did just now)
<img width="1674" alt="image" src="https://github.com/user-attachments/assets/9888ea38-fcc7-4635-a798-c203e3c2661d">

**Comment by oaroki-git** [comment]
updated issue title

**Comment by adriankarlen** [comment]
The css uses your themes colors. In the preview I am using the Rosé Pine Moon theme via Firefox color extension.

**Comment by oaroki-git** [comment]
thanks! (sorry for being stupid lol

**Comment by oaroki-git** [comment]
thanks! (sorry for being stupid lol

**Comment by adriankarlen** [comment]
No problem happy to help!
