### ISSUE TITLE
Border/Margins and outline gone FF 132

### ISSUE THREAD

**Issue by MichaelOli123** [adriankarlen/textfox#34]
After updating to Firefox 132, the "main" window does not have the outline or margins anymore.
<img width="1562" alt="image" src="https://github.com/user-attachments/assets/f3f247c3-ee05-4241-a4e7-be3aa17498e3">

**Comment by adriankarlen** [comment]
Hi, thank you for reporting this issue, I have merged PR that resolves this issue.
