### ISSUE TITLE
"main" margins inconsistent

### ISSUE THREAD

**Issue by MichaelOli123** [adriankarlen/textfox#37]
After the recent tabbox fix, the borders are back but the margin is different compared to before, i.e. main box too large. (sorry for the large image, monitor size 😭)
![image](https://github.com/user-attachments/assets/63e7a3f2-80aa-43f8-8c4d-4f1695dc0e69)

**Comment by adriankarlen** [comment]
I have been unable to recreate this issue. Do you have any other css than textfox in use?

**Comment by adriankarlen** [comment]
What OS:s are you guys on?

**Comment by MichaelOli123** [comment]
I am on MacOS.

**Comment by MichaelOli123** [comment]
Hi @adriankarlen , any luck with this issue?

**Comment by justyeethan** [comment]
Hey @MichaelOli123, I also had this issue, and it seems like for some reason there's a style that overrides the margin and padding for #tabbrowser-tabbox. Adding !important to 8px seemed to have fixed it for me:
<img width="287" alt="image" src="https://github.com/user-attachments/assets/be109c44-5f8c-4090-ac82-07cf801a9084">
<img width="493" alt="image" src="https://github.com/user-attachments/assets/f2f66b68-6768-4413-9cec-d3ff5c8fbff6">


Let me know if this works for you.

**Comment by MichaelOli123** [comment]
@justyeethan Yes, that worked! You should make a pull request with those changes!

**Comment by justyeethan** [comment]
Pr is up for review: #40

**Comment by adriankarlen** [comment]
Thank @justyeethan for fixing this issue, I've had a busy week and have not had time to look in to this as I am still running 131. The PR has now been merged, closing.
