### ISSUE TITLE
Purple theme not being applied

### ISSUE THREAD

**Issue by rohrsben** [adriankarlen/textfox#38]
Hello, textfox is awesome! I don't know much about styling firefox, so I wasn't sure if the purple theme in the screenshots is supposed to automatically get applied?

I installed via the nix module, but I went through and verified `user.js` and `chrome/` are as they should be in my firefox profile just in case. Is there a setting I'm missing, or does textfox not apply the theme and I have to install it?

Thanks for the great work :)

Edit for clarification: everything else about textfox is working fine as far as I can tell.

**Comment by snaeil** [comment]
@rohrsben If I understand you correctly, you might be missing the extra plugin [Firefox Color](https://addons.mozilla.org/de/firefox/addon/firefox-color/]. After its installation, you can set Rose Pine colours, using [this link](https://color.firefox.com/?theme=XQAAAAKPAQAAAAAAAABBqYhm849SCia73laEGccwS-xMDPr3WmqH6mLhhyRv-nu52zZ2ZXxbsGmOEknLoZBVSFanWhsjezxhgdCrK27iduavSwvOOiigQih0UlOvLUeJzf6gowAriRj5ek5rgF5SiG4JPvtsgJ1eq9fw0_eEZstNqCi_ueDgCDy9hfOS3KrRkC6ae0NwhO_atJzPxh7wRFDoNx9VNnYtVQrfpx22kzrOtObs1tq6OGCzJIABASG1Mf0qXeW3fBan5GrGn2dnmoflD1b0AwCHpHP1vY-aNrVHjngbt1trpTwTJE5RtsxZdi0sCBW77jujsGxRsLb-9uYBr-TjDYT_9ZHGrQ).
This could be documented a little bit more extensively, imo.

**Comment by rohrsben** [comment]
Ahh, gotcha! Thanks. I didn't want to try installing a theme in case it conflicted with something that wasn't being set. Good to know there was no issues.

**Comment by adriankarlen** [comment]
I've added improved documentation on the color scheme used, and philosophy of textfox in regards to being theme agnostic.
