### ISSUE TITLE
Some kind of margin around main content when in full screen mode 

### ISSUE THREAD

**Issue by Alan-J-Bibins** [adriankarlen/textfox#42]
![image](https://github.com/user-attachments/assets/cb99813d-f9bc-46c4-8c63-d556bd5a847a)
![image](https://github.com/user-attachments/assets/c819aa77-097b-4566-b9f6-3ce4ba920bea)

I am not entirely sure what this is, I just updated textfox to get all the latest changes and got this issue. I dont use any extensions that tamper with fullscreen content, as far as I am aware. 

Am fairly certain that this might be an issue with the main section's margin value.

Firefox version is 132.0

**Comment by adriankarlen** [comment]
Yeah, this is most likely due to the changes firefox 132 brought and marking margin as `!important`. Will look in to it
