### ISSUE TITLE
UI overlapping the text

### ISSUE THREAD

**Issue by CaptainOddessy** [adriankarlen/textfox#5]
When active the line shouldn't overlap the text as the example image shows. 

![IMG_20241013_001534](https://github.com/user-attachments/assets/f7b4084a-1d0b-4e5f-b03b-871948992ec4)

**Comment by adriankarlen** [comment]
It seems like you don't get the variables that I am getting, perhaps they are only set when using the firefox color extension, will investigate.

**Comment by PierreBorine** [comment]
Can confirm, fresh Firefox doesn't seem to have a --lwt-accent-color variable by default
