### ISSUE TITLE
Removing/setting bg image in Home Content (new tab)

### ISSUE THREAD

**Issue by lcpichette** [adriankarlen/textfox#65]
![2024-12-01@14 10 25 December-01@2x](https://github.com/user-attachments/assets/c2fe912b-2090-4164-8d95-c81093fbf1f7)

Likely this is something that can be removed in config.css, just wondering what that setting is as I'm not seeing it in the README.

Removing Web Search from Home content does remove it, but it also removes the Web Search from the Home content. I don't think I should need to remove that to remove the background image. It'd also be pretty cool if we could change that image to whatever we wanted to.

**Comment by adriankarlen** [comment]
Hi, yeah this happened with the latest FF update, will investigate.
