### ISSUE TITLE
is there a way to unhide the window control buttons

### ISSUE THREAD

**Issue by Amgsdfyhadfgybi** [adriankarlen/textfox#69]
not really used to shortcuts to hide the window

**Comment by adriankarlen** [comment]
If you use horizontal tabs you can simply remove lines 1-4 in the file `tabs.css`. However at the moment when horizontal tabs are hidden the window control buttons go with them.

**Comment by adriankarlen** [comment]
#90 adds an option for this if you are using native vertical tabs or horizontal tabs.
