### ISSUE TITLE
current selection color is very wrong

### ISSUE THREAD

**Issue by jabuxas** [adriankarlen/textfox#8]
is that native to firefox theme?

![image](https://github.com/user-attachments/assets/ceadcfff-6522-4c7a-9c85-4a9f7742a685)

if not, where can i change it in the css files?

**Comment by adriankarlen** [comment]
I think this is related to the same issue as #5. Some variables seems to be set by the Firefox Color extension. I will try to resolve what variables are used and add sensible fallback, perhaps use currentColor more aswell.
